# Use the official Ubuntu 20.04 LTS as the base image
FROM ubuntu:20.04

# Set the maintainer label
LABEL maintainer="Your Name <your_email@example.com>"

# Set environment variables for configuration
ENV NGROK_VERSION 2.3.40
ENV NGROK_AUTH_TOKEN your_auth_token

# Update the package lists and install necessary packages
RUN apt-get update && \
    apt-get install -y wget xvfb xrdp

# Download and install ngrok
RUN wget https://bin.equinox.io/c/${NGROK_AUTH_TOKEN}/ngrok-stable-linux-amd64.zip && \
    unzip ngrok-stable-linux-amd64.zip -d /usr/local/bin && \
    rm ngrok-stable-linux-amd64.zip

# Copy the xrdp configuration file to the correct location
COPY xrdp.ini /etc/xrdp/xrdp.ini

# Expose the RDP port
EXPOSE 3389

# Set the entrypoint command to start the xrdp service
ENTRYPOINT ["xrdp", "--nodaemon"]

# Add a comment to document the purpose of this Dockerfile
# This Dockerfile sets up an Ubuntu-based RDP server with ngrok for remote access
