# Use the official Ubuntu base image
FROM ubuntu:latest

# Set the maintainer label
LABEL maintainer="Your Name <jayyrasst@gmail.com>"

# Set environment variables for configuration
ENV USERNAME=myuser
ENV PASSWORD=mypassword

# Update the package lists and install necessary packages
RUN apt-get update && \
    apt-get install -y \
    ubuntu-desktop \
    tightvncserver \
    xfce4 \
    xfce4-goodies \
    firefox \
    sudo \
    wget \
    curl \
    git \
    nano

# Set the VNC password
RUN echo $PASSWORD | vncpasswd -f > /root/.vnc/passwd && \
    chmod 600 /root/.vnc/passwd

# Create a startup script
RUN echo "#!/bin/bash" > /root/startup.sh && \
    echo "vncserver :1 -geometry 1280x800 -depth 24 && tail -F /root/.vnc/*.log" >> /root/startup.sh && \
    chmod +x /root/startup.sh

# Expose the VNC port
EXPOSE 5901

# Set the entrypoint to start the VNC server
ENTRYPOINT ["/root/startup.sh"]
